language: scala
jdk:
  - oraclejdk8
addons:
  apt: 
    packages:
      - oracle-java8-installer
scala:
  - scala 2.11.6
android:
  components:
    - build-tools-25.0.0
    - android-25
  licenses:
    - android-sdk-license-bcbbd656
script:
  - sbt clean reload android:run
